#!/bin/sh

LOG=athena-i.log
REPORT=athena-i
DIR_LOG=/home/athena/ftp/files/
DIR_ETC=/etc/athena-i

sudo rm -rf $DIR_ETC $DIR_LOG$LOG $DIR_LOG$REPORT

crontab -l|sed 's|@reboot sudo python3 /etc/athena-i/api/api.py >> /home/athena/ftp/files/athena-i.log/api.log &||i'|crontab -
crontab -l|sed 's|@reboot sudo python3 /etc/athena-i/models/manager.py >> /home/athena/ftp/files/athena-i.log/manager.log &||i'|crontab -

sudo reboot now
